# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindoww(object):
    def setupUi(self, MainWindoww):
        MainWindoww.setObjectName("MainWindoww")
        MainWindoww.resize(829, 852)
        MainWindoww.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindoww)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMaximumSize(QtCore.QSize(1677721, 1677721))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icon/images/doctor.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_3)
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(11)
        self.treeWidget.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 1)
        MainWindoww.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindoww)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        MainWindoww.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindoww)
        self.statusbar.setObjectName("statusbar")
        MainWindoww.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindoww)
        QtCore.QMetaObject.connectSlotsByName(MainWindoww)

    def retranslateUi(self, MainWindoww):
        _translate = QtCore.QCoreApplication.translate
        MainWindoww.setWindowTitle(_translate("MainWindoww", "Doctor Screen"))
        self.label_2.setText(_translate("MainWindoww", "Name :"))
        self.label_7.setText(_translate("MainWindoww", "Doctor"))
        self.label_3.setText(_translate("MainWindoww", "Surname"))
        self.label_8.setText(_translate("MainWindoww", "Jo"))
        self.label_5.setText(_translate("MainWindoww", "ID :"))
        self.label_9.setText(_translate("MainWindoww", "11111"))
        self.label_6.setText(_translate("MainWindoww", "Gender :"))
        self.comboBox.setItemText(0, _translate("MainWindoww", "Male"))
        self.comboBox.setItemText(1, _translate("MainWindoww", "Female"))
        self.label.setText(_translate("MainWindoww", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Patients</span></p></body></html>"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindoww", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindoww", "Surname"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindoww", "ID Number"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindoww", "Wife/Husband Name"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindoww", "Wife/Husband ID"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindoww", "John"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("MainWindoww", "Snow"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("MainWindoww", "1"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("MainWindoww", "Lily Snow"))
        self.treeWidget.topLevelItem(0).setText(4, _translate("MainWindoww", "2"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindoww", "Lily"))
        self.treeWidget.topLevelItem(1).setText(1, _translate("MainWindoww", "Snow"))
        self.treeWidget.topLevelItem(1).setText(2, _translate("MainWindoww", "2"))
        self.treeWidget.topLevelItem(1).setText(3, _translate("MainWindoww", "John Snow"))
        self.treeWidget.topLevelItem(1).setText(4, _translate("MainWindoww", "1"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindoww", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindoww", "New Item"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindoww", "New Item"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindoww", "New Item"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindoww", "New Item"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindoww", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("MainWindoww", "Modificate"))
        self.pushButton_2.setText(_translate("MainWindoww", "Delete"))
        self.pushButton.setText(_translate("MainWindoww", "Choose"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindoww = QtWidgets.QMainWindow()
    ui = Ui_MainWindoww()
    ui.setupUi(MainWindoww)
    MainWindoww.show()
    sys.exit(app.exec_())
